### ISSUE TITLE
can you make this plugin multi tool compatible ?

### ISSUE THREAD

**Issue by cristiansavaro** [malnvenshorn/OctoPrint-CostEstimation#10]
![capture](https://user-images.githubusercontent.com/10725599/38763751-05ff87e4-3fab-11e8-97c6-b68d5aaf258a.JPG)

**Comment by malnvenshorn** [comment]
What do you mean? This plugin includes the filament costs of all tools. If you have the filament manager plugin installed and activated in the settings of this plugin it includes the filament costs of all tools with assigned spools.

**Comment by cristiansavaro** [comment]
after the print completed the 2nd tool updated with the info. i guess i was too eager to see the information and hit print too soon. i will close the issue.
