### ISSUE TITLE
[Question] Calculations used

### ISSUE THREAD

**Issue by Stady234** [malnvenshorn/OctoPrint-CostEstimation#21]
Is it possible to see what you used to make the calculations...

I am trying to figure out why i am getting wildly different costs for like parts...

**Comment by malnvenshorn** [comment]
Just take a look at the source code https://github.com/malnvenshorn/OctoPrint-CostEstimation/blob/1b25457ecb77f2a5cd796265ad6d3a7e78f56422/octoprint_costestimation/static/js/costestimation.js#L41-L84

**Comment by Stady234** [comment]
Perfect ! thank you...
