### ISSUE TITLE
Viewing

### ISSUE THREAD

**Issue by ea4eng** [malnvenshorn/OctoPrint-CostEstimation#5]
Good Morning
If it can be, we would need this data to come out only if it is authenticated, being a store we can not tell customers to see how they are doing their work as they also see the actual cost of printing.
We would only like to show it once authenticated. So to speak in the back room.
Thanks for contributing this plugin so necessary and useful.

A greeting.

**Comment by malnvenshorn** [comment]
Added option in version 1.1.0

**Comment by ea4eng** [comment]
Good afternoon, thank you for your work.
But I check that after updating it still presents the actual cost price.
Is it possible that the price comes out on screen only once identified?
I also use the module that cost for customer, in which the price per hour worked is estimated. That is in agreement with the estimated price because it is much higher. Someone may ask why you charge more for something you are getting.
Thank you.

**Comment by ea4eng** [comment]
I had to restart and select to exit.
Very good job and very fast.
Thank you very much.
