### ISSUE TITLE
[Request] Add depreciated printer cost and maintenance.

### ISSUE THREAD

**Issue by MStylesMS** [malnvenshorn/OctoPrint-CostEstimation#7]
This is also a nice plugin and I appreciate that it works with your filament manager app.  

Depending upon how you calculate it, the greatest cost to print is not the filament or the electrical cost, but the cost of the printer plus maintenance.  It would be helpful to be able to include a factor for that, possibly as a function of printing time.

For example, assume you have the purchase price (P), an estimated printer lifespan (L) in hours (h), and estimated cost of maintenace per hour of operation (M).  One sensible equation to determine hourly printing cost (C) would then be:

     C(h) = h * [(P / L) + M]

In my case I'm using a PRUSA MK2sMM and the numbers I'm assuming areL

     P = $1,000
     L = 5,000 hours 
     M = $100 / 500 hours = $0.20

Therefore the printer cost for a 10 hour print would be:

    C(10) = 10 * [(1000 / 5000) + 0.20] = $4.00

I realize these numbers are assumptions, but they are reasonable, non-trivial, and represent a real cost.  

Thanks for your consideration!

**Comment by malnvenshorn** [comment]
Thanks for your post. The depreciation of the printer and the maintenance costs are something I haven't thought about yet and I will definitely add them to the calculation with the next release ;-)

**Comment by MStylesMS** [comment]
Awesome, thanks @malnvenshorn!
