### ISSUE TITLE
Using the costs outside of Octoprint

### ISSUE THREAD

**Issue by Fixel2012** [malnvenshorn/OctoPrint-CostEstimation#8]
Hi,

thank you for you're great work so far!

I would like to use the costs of the print outside of octoprint. Is there a simple way to get them to an other machine inside my network?

It would be enough to add the costs to the telegram plugin. But I have no idea whats needed for that.

Which way would be easier?

Background of my plan:
The Costs get lost if I power off the printer automaticly. So there's no way to get the costs for me. I need a way to save them, the best way would to get them to my phone (telegram).

Is there a way to implement this feature in some kind?

Thank you in advance!

**Comment by malnvenshorn** [comment]
Well you could submit a feature request to the print history plugin, but I don't know if it's still actively supported. In this case the print cost would be saved for each print. 

It is also possible to send the value through the telegram plugin. This can be done e.g. by simply listening for the print started event, reading the print cost and then sending it.

The easiest way would be to select your gcode file and your used filament (if you are using this with the filament manager) again and it will show you the print cost again.

**Comment by Fixel2012** [comment]
Thank you for you're quick answer.

> The easiest way would be to select your gcode file and your used filament (if you are using this with the filament manager) again and it will show you the print cost again.
> 

Well, i didn't know that, thank you! But it's not that comfortable. Would be great to have another solution.


Is it possible to add the plugin to the octoprint api so i can read the Value from an other machine?

Anyway, I will ask the telegram plugin owner to add a feature which displays the costs inside Telegram.
