### ISSUE TITLE
User/project field and print history

### ISSUE THREAD

**Issue by DPastl** [malnvenshorn/OctoPrint-CostEstimation#9]
For internal tracking of costs it would be really useful if one could assign a user or project to the print.  Something similar to the print history plugin that would allow you to download a history of all the prints but with additional fields for cost and project/user.  That way when attempting to charge for maintenance of printers to various projects it would be as simple as downloading a csv and sorting in excel.  

This also allows group environments to track how much each user has printed and what they owe.

**Comment by malnvenshorn** [comment]
I agree, some kind of history could be a good addition to the CostEstimation / FilamentManager plugin. This request pops up from time to time. But I won't integrate this in either of them. If I have time for this it would be a separate plugin.

Currently I'm doing some other projects, therefore I can't say when I have some time to spend.

**Comment by malnvenshorn** [comment]
Closing because it is not directly related to this plugin.
